version: '3'
services:
  redis:
    image: redis:latest
    container_name: chat-redis
    ports:
      - 6379:6379
  chat-app:
    image: chat:1.0
    container_name: chat-app
    ports:
      - 8000:8000
